type: object
required:
  - _id
  - title
  - category
  - ingredients
  - instructions
  - description
  - thumb
  - time
  - area
properties:
  _id:
    type: string
    description: "Recipe's id"
    example: '6462a8f74c3d0ddd28897fcd'
  title:
    type: string
    description: 'Title of the recipe'
    example: 'Battenberg Cake'
  category:
    type: string
    pattern: '^[0-9a-fA-F]{24}$'
    description: 'Identifier of the recipe category'
    example: '6462a6cd4c3d0ddd28897f8f'
  area:
    type: string
    pattern: '^[0-9a-fA-F]{24}$'
    description: 'Identifier of the regional cuisine or country of origin of the recipe'
    example: '6462a6f04c3d0ddd28897f9b'
  instructions:
    type: string
    maxLength: 1200
    description: 'Step-by-step instructions for preparing the recipe'
    example: 'Heat oven to 180C/160C fan/gas 4 and line the base ...'
  description:
    type: string
    description: 'Short description of the recipe'
    example: 'A classic British cake made with almond sponge cake ...'
  thumb:
    type: string
    format: binary
    description: "Dish's photo (max 2MB, only image files)"
  time:
    type: integer
    minimum: 1
    maximum: 360
    description: 'Cooking time in minutes'
    example: 60
  calories:
    type: integer
    minimum: 1
    maximum: 10000
    description: 'Calories per serving'
    example: 230
  ingredients:
    type: array
    description: 'List of ingredients with measurements'
    items:
      type: object
      required:
        - id
        - measure
      properties:
        id:
          type: string
          pattern: '^[0-9a-fA-F]{24}$'
          description: 'Ingredient ID'
          example: '640c2dd963a319ea671e367e'
        measure:
          type: string
          description: 'Amount of the ingredient for this recipe'
          example: '175g'
  owner:
    type: string
    description: 'Id of the user who created the recipe'
    example: '64c8d958249fae54bae90bb9'
  createdAt:
    type: string
    format: date-time
    description: 'Date when the recipe was created'
    example: '2023-03-11T10:25:33Z'
  updatedAt:
    type: string
    format: date-time
    description: 'Date when the recipe was last updated'
    example: '2024-03-03T12:34:31Z'
