openapi: 3.1.0
info:
  version: 1.0.0
  title: Tasteorama
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: A RESTful API for managing a user's recipe list, including creation, adding to favorites, and deletion of recipes. The API also supports filtering by categories and ingredients.
tags:
  - name: Recipes
    description: Recipes operations (getAll, getById, post)
  - name: FavoriteRecipes
    description: FavoriteRecipes operations (getAll, postByID, deleteByID)
  - name: MyRecipes
    description: MyRecipes operations (getAll)
  - name: Auth
    description: Authentication operations (register, login, refresh).
  - name: Users
    description: Users operations (get)
  - name: Сategories
    description: Сategories operations (getAll)
  - name: Ingredients
    description: Ingredients operations (getAll)
servers:
  - url: http://127.0.0.1:3000
  - url: https://tasteorama-backend-dcjy.onrender.com
paths:
  /api/recipes:
    post:
      $ref: ../swagger/paths/recipes/post.yaml
    get:
      $ref: ../swagger/paths/recipes/get.yaml
  # /api/recipes/own:
  #   get:
  #     $ref: ../swagger/paths/recipes/own/get.yaml
  /api/recipes/favorites:
    get:
      $ref: ../swagger/paths/recipes/favorite/get.yaml

  /api/recipes/{id}:
    get:
      $ref: '../swagger/paths/recipes/{id}/get.yaml'
  #   post:
  #     $ref: ../swagger/paths/recipes/{id}/favorite/post.yaml
  #   

  /api/auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml

  /api/auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml

  /api/auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml

  /api/auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml

  /api/auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/send-reset-email.yaml

  /api/auth/reset-pwd:
    post:
      $ref: ../swagger/paths/auth/reset-pwd.yaml

  /api/users:
    get:
      $ref: ../swagger/paths/users/user.yaml

  /api/ingredients:
    get:
      $ref: ../swagger/paths/ingredients/get.yaml

  /api/categories:
    get:
      $ref: ../swagger/paths/category/get.yaml

  /api/recipes/favorite/{recipeId}:
    post:
      $ref: ../swagger/paths/recipes/favorite/{recipeId}/post.yaml
    delete:
      $ref: ../swagger/paths/recipes/favorite/{recipeId}/delete.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      
      schemas:
    Error400:
      $ref: ../swagger/components/schemas/errors/400.yaml
    Error401:
      $ref: ../swagger/components/schemas/errors/401.yaml
    Error404:
      $ref: ../swagger/components/schemas/errors/404.yaml
    Error500:
      $ref: ../swagger/components/schemas/errors/500.yaml
    BadRequestResponse:
      $ref: ../swagger/components/schemas/errors/BadRequestResponse.yaml
      
security:
  - bearerAuth: []
