type: object
properties:
  _id:
    type: string
    description: Recipe id
    example: "66c7c1f4f1b2a9d3e0a12345"
  title:
    type: string
    example: "Pasta Carbonara"
  description:
    type: string
    example: "Classic Italian carbonara with pancetta."
  category:
    type: string
    example: "italian"
  ingredients:
    type: array
    items:
      type: string
    example: ["spaghetti", "eggs", "pecorino", "guanciale"]
  favorite:
    type: boolean
    example: false
  createdAt:
    type: string
    format: date-time
  updatedAt:
    type: string
    format: date-time
required: [_id, title]